### ISSUE TITLE
Components from demo page not working properly in Edge

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#100]
Loading the demo page greets you with the following errors:

```
[object Error]: {description: "Object doesn't support property or method 'attachShadow'", message: "Object doesn't support property or method 'attachShadow'", number: -2146827850, stack: "TypeError: Object doesn't support property or method 'attachShadow' at FocusTrap (http://10.28.51.44:3339/build/calcite-modal.entry.js:151:9) at Anonymous function (http://10.28.51.44:3339/build/dom-860d8016-860d8016.js:19:811) at createElm (http://10.28.51.44:3339/build/core-b48dfbdd.js:666:9) at createElm (http://10.28.51.44:3339/build/core-b48dfbdd.js:684:17) at addVnodes (http://10.28.51.44:3339/build/core-b48dfbdd.js:755:13) at patch (http://10.28.51.44:3339/build/core-b48dfbdd.js:947:13) at renderVdom (http://10.28.51.44:3339/build/core-b48dfbdd.js:1105:5) at updateComponent (http://10.28.51.44:3339/build/core-b48dfbdd.js:1224:17) at update (http://10.28.51.44:3339/build/core-b48dfbdd.js:1197:26) at consumeTimeout (http://10.28.51.44:3339/build/core-b48dfbdd.js:121:13)"}

[object Error]: {description: "Unable to get property 'addEventListener' of undefined or null reference", message: "Unable to get property 'addEventListener' of undefined or null reference", number: -2146823281, stack: "TypeError: Unable to get property 'addEventListener' of undefined or null reference at prototype.componentDidLoad (http://10.28.51.44:3339/build/calcite-modal.entry.js:331:13) at safeCall (http://10.28.51.44:3339/build/core-b48dfbdd.js:1353:13) at postUpdateComponent (http://10.28.51.44:3339/build/core-b48dfbdd.js:1283:17) at updateComponent (http://10.28.51.44:3339/build/core-b48dfbdd.js:1265:5) at update (http://10.28.51.44:3339/build/core-b48dfbdd.js:1197:26) at consumeTimeout (http://10.28.51.44:3339/build/core-b48dfbdd.js:121:13) at flush (http://10.28.51.44:3339/build/core-b48dfbdd.js:145:5)"}

[object Error]: {description: "Unable to get property 'assignedElements' of undefined or null reference", message: "Unable to get property 'assignedElements' of undefined or null reference", number: -2146823281, stack: "TypeError: Unable to get property 'assignedElements' of undefined or null reference at get prototype.tabTitles (http://10.28.51.44:3339/build/calcite-tab-nav.entry.js:117:9) at prototype.componentDidRender (http://10.28.51.44:3339/build/calcite-tab-nav.entry.js:38:9) at safeCall (http://10.28.51.44:3339/build/core-b48dfbdd.js:1353:13) at postUpdateComponent (http://10.28.51.44:3339/build/core-b48dfbdd.js:1272:13) at prototype.s-init (http://10.28.51.44:3339/build/core-b48dfbdd.js:2040:21) at postUpdateComponent (http://10.28.51.44:3339/build/core-b48dfbdd.js:1321:21) at updateComponent (http://10.28.51.44:3339/build/core-b48dfbdd.js:1265:5) at update (http://10.28.51.44:3339/build/core-b48dfbdd.js:1197:26) at consumeTimeout (http://10.28.51.44:3339/build/core-b48dfbdd.js:121:13) at flush (http://10.28.51.44:3339/build/core-b48dfbdd.js:145:5)"}

[object Error]: {description: "Unable to get property 'addEventListener' of undefined or null reference", message: "Unable to get property 'addEventListener' of undefined or null reference", number: -2146823281, stack: "TypeError: Unable to get property 'addEventListener' of undefined or null reference at prototype.componentDidLoad (http://10.28.51.44:3339/build/calcite-modal.entry.js:331:13) at safeCall (http://10.28.51.44:3339/build/core-b48dfbdd.js:1353:13) at postUpdateComponent (http://10.28.51.44:3339/build/core-b48dfbdd.js:1283:17) at prototype.s-init (http://10.28.51.44:3339/build/core-b48dfbdd.js:2040:21) at postUpdateComponent (http://10.28.51.44:3339/build/core-b48dfbdd.js:1321:21) at updateComponent (http://10.28.51.44:3339/build/core-b48dfbdd.js:1265:5) at update (http://10.28.51.44:3339/build/core-b48dfbdd.js:1197:26) at consumeTimeout (http://10.28.51.44:3339/build/core-b48dfbdd.js:121:13) at flush (http://10.28.51.44:3339/build/core-b48dfbdd.js:145:5)"}
```

Tested using Edge Microsoft Edge 44.17763.1.0 and 42.17134.1.0 (thanks @driskull).

Assigning everyone so we can all go through our respective components to do some testing/fixing.

**Comment by paulcpederson** [comment]
I think several of these are from tabs.

**Comment by jcfranco** [comment]
Others may be affected. I only tested a few in isolation and noticed that `<calcite-switch>` isn't working properly for the following cases:

* `Switch with no wrapping label.`
* `With a proxy input element and changes on click.`

`<calcite-radio-group>` isn't working properly for the `External inputs` case.

**Comment by vcolavin** [comment]
@jcfranco Interesting, I fixed an identical bug on `calcite-checkbox`, and I remember fixing it for `calcite-switch` too. Maybe I forgot to push that commit; I'll check.
https://github.com/Esri/calcite-components/issues/67

**Comment by vcolavin** [comment]
https://github.com/Esri/calcite-components/blob/master/src/components/calcite-switch/calcite-switch.tsx#L109-L111

Looks like my fix for #67 exists in `calcite-switch` as well, so maybe this is a separate bug with a similar symptom.

**Comment by patrickarlt** [comment]
I've resolved the issues with tabs as a part of https://github.com/Esri/calcite-components/pull/105.

**Comment by macandcheese** [comment]
Closing this as we've opened individual issues for all known Edge bugs, please add individual issues for anything else :)
