### ISSUE TITLE
Bug: Unregister events used for tabs are not caught when component is removed from DOM

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#1365]
### Summary

Bug: Unregister events used for tabs are not caught when component is removed from DOM

### Expected Behavior

There are no warnings emitted during tests about emitting on elements no longer in the DOM.

We may want to evaluate all the events with "register" and "unregister" and instead either...

- Emit on the document
- Use an observer instead of these events

### Reproduction Steps

1. Run the tests
2. Notice the warnings listed below

```
● Console
    console.warn
      STENCIL: The "calciteTabTitleUnregister" event was emitted, but the dispatcher node is no longer connected to the dom. 
      Location: http://localhost:3333/build/index-c14fe7c7.js:2699:70
      at t (node_modules/@stencil/core/testing/index.js:3685:67)
      at node_modules/@stencil/core/testing/index.js:3686:5
      at node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
          at Array.map (<anonymous>)
      at Object.emit (node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
      at Page.emit (node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
      at Page._addConsoleMessage (node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:798:14)
      at Page._onConsoleAPI (node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:741:14)
    console.warn
      STENCIL: The "calciteTabTitleUnregister" event was emitted, but the dispatcher node is no longer connected to the dom. 
      Location: http://localhost:3333/build/index-c14fe7c7.js:2699:70
      at t (node_modules/@stencil/core/testing/index.js:3685:67)
      at node_modules/@stencil/core/testing/index.js:3686:5
      at node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
          at Array.map (<anonymous>)
      at Object.emit (node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
      at Page.emit (node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
      at Page._addConsoleMessage (node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:798:14)
      at Page._onConsoleAPI (node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:741:14)
    console.warn
      STENCIL: The "calciteTabUnregister" event was emitted, but the dispatcher node is no longer connected to the dom. 
      Location: http://localhost:3333/build/index-c14fe7c7.js:2699:70
      at t (node_modules/@stencil/core/testing/index.js:3685:67)
      at node_modules/@stencil/core/testing/index.js:3686:5
      at node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
          at Array.map (<anonymous>)
      at Object.emit (node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
      at Page.emit (node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
      at Page._addConsoleMessage (node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:798:14)
      at Page._onConsoleAPI (node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:741:14)
    console.warn
      STENCIL: The "calciteTabUnregister" event was emitted, but the dispatcher node is no longer connected to the dom. 
      Location: http://localhost:3333/build/index-c14fe7c7.js:2699:70
      at t (node_modules/@stencil/core/testing/index.js:3685:67)
      at node_modules/@stencil/core/testing/index.js:3686:5
      at node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
          at Array.map (<anonymous>)
      at Object.emit (node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
      at Page.emit (node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
      at Page._addConsoleMessage (node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:798:14)
```

### Relevant Info 

https://github.com/Esri/calcite-components/pull/1364

**Comment by driskull** [comment]
For now, I opened a PR to move the events to the document. However, I think we should investigate using an observer instead of these events.

https://github.com/Esri/calcite-components/pull/1372

**Comment by caripizza** [comment]
Verified fixed while running tests on my local master branch just now, and I also confirmed with Matt - closing.
