### ISSUE TITLE
Unstable Test: color-picker tests timing out

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#1998]
## Summary

**Which component?:** calcite-color-picker

**Which test(s)?:** 

Varied between runs, but some of these are: 

**Test error:**

```
FAIL src/components/calcite-color-picker/calcite-color-picker.e2e.ts (336.948 s)
  ● calcite-color-picker › color inputs › color gets propagated to support inputs › when no-color › restores previous color value when a nudge key is pressed
    : Timeout - Async callback was not invoked within the 30000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 30000 ms timeout specified by jest.setTimeout.Error:
      850 |         });
      851 | 
    > 852 |         it("restores previous color value when a nudge key is pressed", async () => {
          |         ^
      853 |           const consistentRgbHsvChannelValue = "0";
      854 |           const initialValue = "#".padEnd(7, consistentRgbHsvChannelValue);
      855 | 
      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (src/components/calcite-color-picker/calcite-color-picker.e2e.ts:852:9)
  ● calcite-color-picker › color storage › allows saving unique colors
    The page was already closed
      506 | 
      507 |       await inputOrHexInput.type(value);
    > 508 |       await page.waitForChanges();
          |                  ^
      509 | 
      510 |       await page.keyboard.press("Enter");
      511 |       await page.waitForChanges();
      at Page.r (node_modules/@stencil/core/testing/index.js:3793:11)
      at clearAndEnterValue (src/components/calcite-color-picker/calcite-color-picker.e2e.ts:508:18)
      at assertChannelValueNudge (src/components/calcite-color-picker/calcite-color-picker.e2e.ts:872:13)
      at Object.<anonymous> (src/components/calcite-color-picker/calcite-color-picker.e2e.ts:911:11)
  ● calcite-color-picker › color storage › loads saved colors
    The page was already closed
      506 | 
      507 |       await inputOrHexInput.type(value);
    > 508 |       await page.waitForChanges();
          |                  ^
      509 | 
      510 |       await page.keyboard.press("Enter");
      511 |       await page.waitForChanges();
      at Page.r (node_modules/@stencil/core/testing/index.js:3793:11)
      at clearAndEnterValue (src/components/calcite-color-picker/calcite-color-picker.e2e.ts:508:18)
      at assertChannelValueNudge (src/components/calcite-color-picker/calcite-color-picker.e2e.ts:872:13)
      at Object.<anonymous> (src/components/calcite-color-picker/calcite-color-picker.e2e.ts:911:11)
  ● calcite-color-picker ��� color storage › allows removing stored colors
    The page was already closed
      506 | 
      507 |       await inputOrHexInput.type(value);
    > 508 |       await page.waitForChanges();
          |                  ^
      509 | 
      510 |       await page.keyboard.press("Enter");
      511 |       await page.waitForChanges();
      at Page.r (node_modules/@stencil/core/testing/index.js:3793:11)
      at clearAndEnterValue (src/components/calcite-color-picker/calcite-color-picker.e2e.ts:508:18)
      at assertChannelValueNudge (src/components/calcite-color-picker/calcite-color-picker.e2e.ts:872:13)
      at Object.<anonymous> (src/components/calcite-color-picker/calcite-color-picker.e2e.ts:911:11)
  ● calcite-color-picker › color storage › does not allow saving/removing when no-color is set
    The page was already closed
      506 | 
      507 |       await inputOrHexInput.type(value);
    > 508 |       await page.waitForChanges();
          |                  ^
      509 | 
      510 |       await page.keyboard.press("Enter");
      511 |       await page.waitForChanges();
      at Page.r (node_modules/@stencil/core/testing/index.js:3793:11)
      at clearAndEnterValue (src/components/calcite-color-picker/calcite-color-picker.e2e.ts:508:18)
      at assertChannelValueNudge (src/components/calcite-color-picker/calcite-color-picker.e2e.ts:872:13)
      at Object.<anonymous> (src/components/calcite-color-picker/calcite-color-picker.e2e.ts:911:11)
```

**PR that skipped the test:** #1995

**Comment by jcfranco** [comment]
Closing as self-verified.
