### ISSUE TITLE
Bug: Calcite Components incompatible with Webpack 5

### ISSUE THREAD

**Issue by bsnider** [Esri/calcite-components#2260]
### Actual Behavior

I am trying to incorporate Calcite Components into a Webpack 5 app.  After following the steps outlined in the readme and then serving the app, I get the following error: 

`[webpack-cli] TypeError: compiler.plugin is not a function
    at StencilPlugin.apply (C:\projects\R9-CentralBasin\node_modules\@stencil\webpack\dist\index.js:14:18)      
    at createCompiler (C:\projects\R9-CentralBasin\node_modules\webpack\lib\webpack.js:71:12)
    at create (C:\projects\R9-CentralBasin\node_modules\webpack\lib\webpack.js:118:16)
    at webpack (C:\projects\R9-CentralBasin\node_modules\webpack\lib\webpack.js:142:32)
    at WebpackCLI.f [as webpack] (C:\projects\R9-CentralBasin\node_modules\webpack\lib\index.js:54:15)
    at WebpackCLI.createCompiler (C:\projects\R9-CentralBasin\node_modules\webpack-cli\lib\webpack-cli.js:1847:29)
    at async Command.<anonymous> (C:\projects\R9-CentralBasin\node_modules\@webpack-cli\serve\lib\index.js:81:30)
    at async Promise.all (index 1)
    at async Command.<anonymous> (C:\projects\R9-CentralBasin\node_modules\webpack-cli\lib\webpack-cli.js:1284:13)`

### Expected Behavior

It should work. 

### Reproduction Steps or Sample

Follow these steps: https://github.com/Esri/calcite-components#webpack

### Relevant Info

_Version_: `@esri/calcite-components@1.0.0-beta.54`, `@stencil/webpack@0.0.6`, `webpack@5.31.0`

- [ ] CDN
- [x] NPM package

**Comment by jcfranco** [comment]
@bsnider Thanks for reporting this. Could you provide us with a repro case showing your webpack configuration?

**Comment by bsnider** [comment]
@jcfranco sorry for the delay.  Here's a repro case.  If line 114 in webpack.config is commented out, it'll compile: https://github.com/USEPA/R9-CentralBasin/blob/calcite-comps-repro/webpack.config.js#L114

**Comment by jcfranco** [comment]
Took a look at this and this is an issue with the plugin. It has not been updated to work w/ Webpack 5. I've submitted a PR in the meantime: https://github.com/ionic-team/stencil-webpack/pull/9. 

Interestingly, after submitting the PR, I found out that there's a fork of the plugin that works w/ version 5: https://github.com/GenesysPureConnect/stencil-webpack

**Comment by jcfranco** [comment]
Closing as this is outside of the project's scope and I have already submitted a PR and suggested an alternative plugin to use.
