### ISSUE TITLE
Unstable Tests: calcite-input "number locale support"

### ISSUE THREAD

**Issue by caripizza** [Esri/calcite-components#2323]
## Summary
The following e2e tests are failing now that the project is using a newer node version (v14.17.1):
https://github.com/Esri/calcite-components/blob/master/src/components/calcite-input/calcite-input.e2e.ts#L745-L818

It seems like Puppeteer is not using the requested locale. Instead it's using the default English locale to format a number:
```javascript
// ex 1.
console.log(
   new Intl.NumberFormat("nb", {​​​​​​​​
     minimumFractionDigits: 0,
     maximumFractionDigits: 20
   }​​​​​​​​).format("1234.56")
);
// Chrome browser returns "1 234,56"
// but the Stencil test run returns "1,234.56"

// ex 2.
const count = 26254.39;
const date = new Date("2012-05-24")
function log(locale) {
  console.log(
    `${new Intl.DateTimeFormat(locale).format(date)} ${new Intl.NumberFormat(locale).format(count)}`
  );
}
log("nb") // returns "23.5.2012 26 254,39" in Chrome console
// but returns "5/23/2012 26,254.39" in e2e test
```
Since `localizeNumberString` function calls the Intl browser api in `createLocaleNumberFormatter`, and the tests don't run on top of the browser, they run under Node.js - the formatted number behavior is different; we may need to add a polyfill/package to get the full locale support.

**Which component?:**
calcite-input.e2e.ts

**Which test(s)?:** 
The "number locale support" describe block:
https://github.com/Esri/calcite-components/blob/master/src/components/calcite-input/calcite-input.e2e.ts#L745-L818

**Test error:**
```
Summary of all failing tests
FAIL src/components/calcite-input/calcite-input.e2e.ts (396.379 s)
  ● calcite-input › number locale support › displays group and decimal separator on initial load for es-MX locale using opt-in prop
    expect(received).toBe(expected) // Object.is equality
    Expected: "1,234.56"
    Received: "1234.56"
      765 | 
      766 |           expect(await calciteInput.getProperty("value")).toBe(value);
    > 767 |           expect(await input.getProperty("value")).toBe(localizeNumberString(value, locale, true));
          |                                                    ^
      768 |         });
      769 | 
      770 |         it(`allows typing valid decimal characters for ${locale} locale`, async () => {
      at Object.<anonymous> (src/components/calcite-input/calcite-input.e2e.ts:767:52)
          at runMicrotasks (<anonymous>)
  ● calcite-input › number locale support › displays decimal separator on initial load for nb locale
    expect(received).toBe(expected) // Object.is equality
    Expected: "1234.56"
    Received: "1234,56"
      753 | 
      754 |           expect(await calciteInput.getProperty("value")).toBe(value);
    > 755 |           expect(await input.getProperty("value")).toBe(localizeNumberString(value, locale));
          |                                                    ^
      756 |         });
      757 | 
      758 |         it(`displays group and decimal separator on initial load for ${locale} locale using opt-in prop`, async () => {
      at Object.<anonymous> (src/components/calcite-input/calcite-input.e2e.ts:755:52)
          at runMicrotasks (<anonymous>)
  ● calcite-input › number locale support › displays group and decimal separator on initial load for nb locale using opt-in prop
    expect(received).toBe(expected) // Object.is equality
    Expected: "1,234.56"
    Received: "1 234,56"
      765 | 
      766 |           expect(await calciteInput.getProperty("value")).toBe(value);
    > 767 |           expect(await input.getProperty("value")).toBe(localizeNumberString(value, locale, true));
          |                                                    ^
      768 |         });
      769 | 
      770 |         it(`allows typing valid decimal characters for ${locale} locale`, async () => {
      at Object.<anonymous> (src/components/calcite-input/calcite-input.e2e.ts:767:52)
          at runMicrotasks (<anonymous>)
  ● calcite-input › number locale support › allows typing valid decimal characters for nb locale
    expect(received).toBe(expected) // Object.is equality
    Expected: "1234.56"
    Received: "1234,56"
      784 | 
      785 |           expect(await calciteInput.getProperty("value")).toBe(`1234.56`);
    > 786 |           expect(await input.getProperty("value")).toBe(localizeNumberString(unformattedValue, locale));
          |                                                    ^
      787 |         });
      788 | 
      789 |         it(`displays correct formatted value when the value is changed programatically for ${locale} locale`, async () => {
      at Object.<anonymous> (src/components/calcite-input/calcite-input.e2e.ts:786:52)
          at runMicrotasks (<anonymous>)
  ● calcite-input › number locale support › displays correct formatted value when the value is changed programatically for nb locale
    expect(received).toBe(expected) // Object.is equality
    Expected: "1234567.891011"
    Received: "1234567,891011"
      814 | 
      815 |           expect(await calciteInput.getProperty("value")).toBe(assertedValue);
    > 816 |           expect(await internalLocaleInput.getProperty("value")).toBe(localizeNumberString(assertedValue, locale));
          |                                                                  ^
      817 |         });
      818 |       });
      819 | 
      at Object.<anonymous> (src/components/calcite-input/calcite-input.e2e.ts:816:66)
          at runMicrotasks (<anonymous>)
```

**PR that skipped the test:** pr #2324

## Additional Info 
The problematic locales for these tests are "nb" and "es-MX".

**Comment by caripizza** [comment]
cc @driskull @eriklharper

**Comment by caripizza** [comment]
I'll open a pr to comment these `expects` out for now

**Comment by driskull** [comment]
Thanks for taking care of this @caripizza 🍕 🥇

**Comment by julio8a** [comment]
Verified on Travis, no failed tests.
