### ISSUE TITLE
`calcite-chip` does not render when the parent is a custom element / shadow root

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-components#6856]
### Actual Behavior

When the chip is a direct child in the shadow root, it will not render.

### Expected Behavior

It should render, since 1.0.3 is not supposed to have breaking changes / it was not documented

### Reproduction Sample

https://codepen.io/eborgen/pen/OJBmJQe?editors=1010

### Reproduction Steps

Open the codepen, observe it is not rendering

### Reproduction Version

1.3.0

### Regression?

1.2.0

### Priority impact

p0 - emergency

### Impact

Need a workaround or patch as soon as possible

### Esri team

ArcGIS Web Analysis

**Comment by ethanbdev** [comment]
The issue is there here:
https://github.com/Esri/calcite-components/pull/6075/files#diff-b237b0dcdb25a0941df7fe4dc75a403c120893bee940115495a9b6216358d92cR201

Will return `null` if the parent element is across the shadow boundary. I.e.
```
<custom-parent>
  <shadow-root>
    <calcite-chip />
  </shadow-root>
</custom-parent>
```

Then, when it gets to the render function,
https://github.com/Esri/calcite-components/pull/6075/files#diff-b237b0dcdb25a0941df7fe4dc75a403c120893bee940115495a9b6216358d92cR201

Gives a reference error
```
TypeError: Cannot read properties of null (reading 'label')
    at y.render (p-41dbef13.entry.js:6:3490)
    at V (p-21300df2.js:6:7216)
    at q (p-21300df2.js:6:7062)
    at p-21300df2.js:6:6879 <calcite-chip class=​"analysis-chip-button" calcite-hydrated>​…​</calcite-chip>​flex
fe @ p-21300df2.js:6
```

Maybe it should use optional chaining as I don't think a parent element should be required

**Comment by ethanbdev** [comment]
Workaround is to insert a div wrapping the chip(s), so they have a light-dom parent 👍
